artifacts_root: artifact
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/KetkiMD/MLOPS-DVC-Pipeline-With-Deployments-AWS-Chicken-Disease-Classification-/blob/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
