artifacts_root:artifact
data_ingestion:
root_dir: artifacts/data_ingestion
source_url: C:/Users/Dell/Desktop/Classification_of_Chicken_Disease/Chicken-fecal-images
local_data_file: artifacts/data_ingestion/data.zip
unzip_dir: artifacts/data_ingestion