artifacts_root:artifact
data_ingestion:
root_dir: artifacts/data_ingestion
source_url: MLOPS-DVC-Pipeline-With-Deployments-AWS-Chicken-Disease-Classification-/Chicken-fecal-images
local_data_file: artifacts/data_ingestion/data.zip
unzip_dir: artifacts/data_ingestion