artifacts_root: artifact
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: C:/Users/Dell/Desktop/MLOPS-DVC-Pipeline-With-Deployments-AWS-Chicken-Disease-Classification-/Chicken_fecal_images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
